"""tools/check_hygiene.py: what a pull request publishes stays clean (CONTRIBUTING.md, "Branches, commits and pull requests")."""
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, os.path.join(ROOT, "tools"))
import check_hygiene as ch  # noqa: E402
import json  # noqa: E402

DIPADA = "57390069+dipada@users.noreply.github.com"
SID = "session_" + "01AbCdEfGhIjKlMnOpQrSt"  # built here: the shape of a session id, none real


def commit(message="fix: a thing", author=DIPADA, committer=DIPADA):
    return {"sha": "0123456789abcdef", "author": author, "committer": committer, "message": message}


class Text(unittest.TestCase):
    def found(self, text):
        return ch.text_findings(text, "x")

    def test_an_e_mail_address_that_leads_to_a_person(self):
        for text in ("write to mario.rossi@" + "gmail.com", "contact: someone@company.it", "Signed-off-by: X <x@corp.example.org.uk>"):
            self.assertEqual([f.split(": ", 1)[1] for f in self.found(text)], ["an e-mail address (only the GitHub noreply ones may appear)"], text)

    def test_what_is_refused(self):
        for text in ("fix: a thing\n\nCo-Authored-By: Someone <someone@example.com>",
                     "body\n\n\U0001F916 Generated with [A Tool](https://example.com/tool)",
                     "body\n\n---\n_Generated by [A Tool](https://example.com/code/x)_",
                     "see https://example.com/code/" + SID,
                     "the contract is in /tmp/claude-0/x/scratchpad/plan.md",
                     "written with Claude Code", "an Anthropic model", "subagents use Sonnet", "Haiku for the small steps",
                     "a sub-agent did it", "opus for the hard ones"):
            self.assertTrue(self.found(text), text)

    def test_what_is_fine(self):
        for text in ("docs: follow CLAUDE.md and CONTRIBUTING.md", "generated by aisetup itself",
                     "regenerated with the commands in CONTRIBUTING.md", "the session of the web view (a cookie)",
                     "user agent string", "co-author of the original parser", "Generated with `python3 tools/ansi2svg.py`",
                     "Commits as dipada <57390069+dipada@users.noreply.github.com>", "noreply@github.com", "user@1000.service",
                     "systemctl mask getty@tty1.service", "s@db.example.com", "http://user:pw@127.0.0.1:8080/v1", "a@b.invalid"):
            self.assertEqual(self.found(text), [], text)

    def test_the_line_and_the_reason_are_named(self):
        f = self.found("one\ntwo\nCo-authored-by: x <y@example.com>\n")
        self.assertEqual(len(f), 1)
        self.assertIn("x, line 3: a co-author trailer", f[0])


class Commits(unittest.TestCase):
    def test_the_two_authors_and_github_as_committer(self):
        self.assertEqual(ch.commit_findings([commit(), commit(author="4461018+give-jd@users.noreply.github.com"),
                                             commit(committer="noreply@github.com")]), [])

    def test_anyone_else_is_refused_as_author_or_committer(self):
        f = ch.commit_findings([commit(author="someone@example.com"), commit(committer="bot@example.com"),
                                commit(author="noreply@github.com")])
        self.assertEqual(len(f), 3, f)
        self.assertTrue(all(x.startswith("commit 0123456: ") for x in f))

    def test_a_real_name_is_refused_and_never_repeated(self):
        name = "Mario" + " Rossi"  # built here: any name that is not one of the repository's handles
        f = ch.commit_findings([dict(commit(), author_name=name), dict(commit(), committer_name=name),
                                dict(commit(), author_name="JD", committer_name="GitHub")])
        self.assertEqual(len(f), 2, f)
        self.assertFalse([x for x in f if "Mario" in x or "Rossi" in x], "the public log must not carry the name it refuses")

    def test_an_address_is_never_repeated(self):
        f = ch.commit_findings([commit(author="mario.rossi@" + "mail.example.it")])
        self.assertEqual(f, ["commit 0123456: the author's address is not a noreply address of the repository's accounts"])

    def test_the_message_is_checked(self):
        self.assertTrue(ch.commit_findings([commit("feat: x\n\nCo-authored-by: a <b@example.com>")]))


class Diff(unittest.TestCase):
    DIFF = ("diff --git a/docs/A.md b/docs/A.md\n--- a/docs/A.md\n+++ b/docs/A.md\n@@ -10,0 +11,2 @@\n+fine\n+written with Claude Code\n"
            "diff --git a/tools/check_hygiene.py b/tools/check_hygiene.py\n--- a/tools/check_hygiene.py\n+++ b/tools/check_hygiene.py\n"
            "@@ -1,0 +2 @@\n+claude\n"
            "diff --git a/gone.md b/gone.md\n--- a/gone.md\n+++ /dev/null\n@@ -1 +0,0 @@\n-claude\n")

    def test_added_lines_with_their_file_and_line_the_checker_itself_skipped(self):
        f = ch.diff_findings(self.DIFF)
        self.assertEqual(len(f), 1, f)
        self.assertIn("docs/A.md, line 12: the name of a tool", f[0])

    def test_an_added_line_that_looks_like_a_header_is_still_a_line(self):
        f = ch.diff_findings("--- a/x.md\n+++ b/x.md\n@@ -0,0 +1,2 @@\n+++ claude\n+ok\n")
        self.assertEqual(len(f), 1, f)
        self.assertIn("x.md, line 1:", f[0])


@unittest.skipUnless(shutil.which("git"), "git is not installed")
class OnARepository(unittest.TestCase):
    """main() against a real repository: a clean branch passes, a footer in a commit, a line or the description fails."""

    def git(self, *a, env=None):
        e = dict(os.environ, GIT_AUTHOR_NAME="dipada", GIT_AUTHOR_EMAIL=DIPADA, GIT_COMMITTER_NAME="dipada",
                 GIT_COMMITTER_EMAIL=DIPADA, GIT_CONFIG_GLOBAL=self.cfg, GIT_CONFIG_NOSYSTEM="1")
        e.update(env or {})
        return subprocess.run(("git", "-C", self.d) + a, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              env=e, encoding="utf-8").stdout

    def write_commit(self, name, text, message, env=None):
        with open(os.path.join(self.d, name), "w", encoding="utf-8") as f:
            f.write(text)
        self.git("add", name)
        self.git("-c", "commit.gpgsign=false", "commit", "-q", "-m", message, env=env)

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.d = os.path.join(self.tmp.name, "repo")
        self.cfg = os.path.join(self.tmp.name, "gitconfig")  # no global settings of this machine (signing, hooks, another identity)
        open(self.cfg, "w").close()
        os.mkdir(self.d)
        self.git("init", "-q", "-b", "main")
        self.write_commit("README.md", "# x\n", "docs: start")
        self.git("checkout", "-q", "-b", "feat/x")
        self.cwd = os.getcwd()
        os.chdir(self.d)

    def tearDown(self):
        os.chdir(self.cwd)
        self.tmp.cleanup()

    def event(self, body, title="feat: x"):
        """The pull_request event file GitHub gives the workflow ($GITHUB_EVENT_PATH)."""
        p = os.path.join(self.tmp.name, "event.json")
        base, head = self.git("rev-parse", "main").strip(), self.git("rev-parse", "HEAD").strip()
        with open(p, "w", encoding="utf-8") as f:
            json.dump({"pull_request": {"title": title, "body": body, "base": {"sha": base}, "head": {"sha": head}}}, f)
        return p

    def run_main(self, *a):
        import contextlib
        import io
        out = io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(io.StringIO()):
            rc = ch.main(list(a))
        return rc, out.getvalue()

    def test_a_clean_branch_passes(self):
        self.write_commit("a.txt", "fine\n", "feat: a fine change\n\nWhy it is needed.")
        self.assertEqual(self.run_main("--event", self.event("What and why.\n\nTests: all pass.")), (0, ""))
        self.assertEqual(self.run_main("--event", self.event(None)), (0, ""))  # a pull request without a description

    def test_a_footer_a_line_an_author_and_the_description_are_each_found(self):
        self.write_commit("a.txt", "see /tmp/claude-0/s/scratchpad/x\n", "feat: x\n\nCo-Authored-By: A Tool <tool@example.com>",
                          env={"GIT_AUTHOR_EMAIL": "tool@example.com"})
        rc, out = self.run_main("--event", self.event("body\n\nhttps://example.com/code/" + SID, title="feat: by a sub-agent"))
        self.assertEqual(rc, 1)
        for what in ("the author's address is not", "message, line 3: a co-author trailer", "a.txt, line 1: a path",
                     "pull request description, line 3: a session id", "pull request title, line 1: how the work was split"):
            self.assertIn(what, out)
        for secret in (SID, "scratchpad", "Co-Authored-By", "sub-agent"):
            self.assertNotIn(secret, out, "a finding never repeats what it refuses: the CI log is public")
        self.assertEqual(self.run_main("--base", "main", "--head", "HEAD")[0], 1)  # the same branch, without the event

    def test_a_text_file_and_the_usage(self):
        p = os.path.join(self.d, "draft.md")
        with open(p, "w", encoding="utf-8") as f:
            f.write("ok\n\n\U0001F916 Generated with [A Tool](https://example.com/tool)\n")
        rc, out = self.run_main("--text", p)
        self.assertEqual(rc, 1)
        self.assertIn("draft.md, line 3: a generated-with footer", out)
        self.assertEqual(self.run_main("--base", "main")[0], 2)
        self.assertEqual(self.run_main()[0], 2)


class Workflow(unittest.TestCase):
    def setUp(self):
        with open(os.path.join(ROOT, ".github", "workflows", "hygiene.yml"), encoding="utf-8") as f:
            self.src = f.read()

    def test_every_pull_request_and_every_edit_of_its_text(self):
        self.assertIn("types: [opened, edited, reopened, synchronize]", self.src)
        self.assertIn("fetch-depth: 0", self.src)
        self.assertIn("contents: read", self.src)

    def test_the_text_is_read_from_the_event_file_never_pasted_nor_put_in_the_printed_environment(self):
        runs = [ln for ln in self.src.splitlines() if ln.strip().startswith("run:")]
        self.assertEqual(runs, ['        run: python3 tools/check_hygiene.py --event "$GITHUB_EVENT_PATH"'])
        for never in ("pull_request.body", "pull_request.title", "env:"):
            self.assertNotIn(never, self.src)

    def test_the_action_is_pinned_by_commit_like_the_release(self):
        self.assertTrue(re.search(r"uses: actions/checkout@[0-9a-f]{40} # v\d", self.src))


class TheRules(unittest.TestCase):
    def test_contributing_and_claude_md_say_the_same_and_the_archives_carry_neither(self):
        with open(os.path.join(ROOT, "CONTRIBUTING.md"), encoding="utf-8") as f:
            contributing = f.read()
        with open(os.path.join(ROOT, "CLAUDE.md"), encoding="utf-8") as f:
            agents = f.read()
        self.assertIn("## Branches, commits and pull requests", contributing)
        self.assertIn("tools/check_hygiene.py", contributing)
        self.assertIn("CONTRIBUTING.md", agents)
        self.assertIn(DIPADA, agents)
        self.assertEqual(ch.text_findings(contributing, "CONTRIBUTING.md"), [])
        self.assertEqual(ch.text_findings(agents, "CLAUDE.md"), [])
        sys.path.insert(0, os.path.join(ROOT, "tools"))
        import build_release
        self.assertIn("CLAUDE.md", build_release.DEV_FILES)
        self.assertIn("CONTRIBUTING.md", build_release.DEV_FILES)


if __name__ == "__main__":
    unittest.main()
